### ISSUE TITLE
No leading zero on CRC16 code

### ISSUE THREAD

**Issue by alvfig** [Alexsussa/pixqrcodegen#2]
When the first digit of the CRC16 code is zero, it is missing on its resulting formatted string, which length is 3 instead of 4.

Example:

```py
>>> import pixqrcodegen
>>> pld = pixqrcodegen.Payload('MYSELF', '3', '0.01', 'HERE', '*')
>>> pld.gerarPayload()
00020126230014BR.GOV.BCB.PIX0101352040000530398654040.015802BR5906MYSELF6004HERE62
050501*6304B8B
>>>

**Comment by Alexsussa** [comment]
> 
Thank you for your observation for the solution on that problem.
